[package]
name = "idgend"
version = "0.1.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
publish = false
readme = "README.md"
license = "MIT"
description = "ğŸ®ğŸºç®€å•ç²—æš´çš„é¢„ç”Ÿæˆå”¯ä¸€çº¯æ•°å­—IDç”ŸæˆæœåŠ¡ã€‚"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.27"
crossbeam = "0.7.3"
env_logger = "0.7.1"
futures = "0.3.4"
hyper = "0.13.4"
itertools = "0.9.0"
log = "0.4.8"
num_cpus = "1.12.0"
prost = "0.6.1"
rand = "0.7.3"
rocksdb = "0.13.0"
structopt = "0.3.12"
tokio = { version = "0.2.13", features = ["full"] }
tonic = "0.1.1"

[build-dependencies]
anyhow = "1.0.26"
tonic-build = "0.1.1"
